name: hiringpeak-app

services:
  postgres:
    restart: always
    container_name: hiringpeak-postgres
    image: postgres:16-alpine
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - ./apps/api/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data
