name: hiringpeak-app
services:
  postgres:
    restart: unless-stopped
    container_name: hiringpeak-postgres
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./apps/api/.env
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: hiringpeak
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
