export enum FeatureFlag {
  LOGIN_ENABLED = 'LOGIN_ENABLED',
  GOOGLE_LOGIN_ENABLED = 'GOOGLE_LOGIN_ENABLED',
  ADVANCED_ANALYTICS = 'ADVANCED_ANALYTICS',
  BETA_DASHBOARD = 'BETA_DASHBOARD',
  AI_VACANCY_FLOW = 'AI_VACANCY_FLOW',
  AI_VACANCY_PERSISTENCE = 'AI_VACANCY_PERSISTENCE',
}
